version: 0.2

env:
  variables:
    TEST_ENV: "dev"
  parameter-store:
    LOGIN_PASSWORD: "dockerLoginPassword"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
  pre_build:
    commands:
      #- echo Entered the pre_build phase...
      #- docker login ?u User ?p $LOGIN_PASSWORD
      #- pwd
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn install
      - pwd
      - bash test.sh ${TEST_ENV}
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
